### ISSUE TITLE
External storage denied

### ISSUE THREAD

**Issue by Areg472** [mardous/BoomingMusic#10]
So I'm trying to whitelist/blacklist folders, but I can't it needs an all files access permission, I tried through the settings app, not there

**Comment by mardous** [comment]
Are the folders you are trying to whitelist/blacklist on an SD card or device storage?

**Comment by xpbl** [comment]
I have multiple formats of my music leading to duplicates everywhere and I tried to setup a whitelist and it won't let me. I'm unable to give the app external storage privileges. Not from settings, not from the app. Seems to be a manifest issue

**Comment by xpbl** [comment]
It could also just because I'm on Android 15

**Comment by mardous** [comment]
Yes. It seems to be a problem with how the app handles permissions at that point. I'll look into it.

**Comment by mardous** [comment]
The issue has been fixed, thank you for reporting it. The fix will be included in the next update.

**Comment by coxackie** [comment]
Using 1.0.4, but still not able to access SD card folder to whitelist folders there. Am I missing something?

**Comment by mardous** [comment]
> Using 1.0.4, but still not able to access SD card folder to whitelist folders there. Am I missing something? 

Are you getting a permission denied message or are you simply not able to see the SD card in the folder selection dialog?

It would be very helpful if you could attach a screenshot.

**Comment by coxackie** [comment]
![Image](https://github.com/user-attachments/assets/055ef76b-193a-4f63-96f0-8ce911c1b676)

No permission denied message. Just that SD card does not appear in the selection dialog. I want to only whitelist the Music folder in the SD card. Only the internal storage is selectable. (When I go one folder up, there is nothing there.) Note, however, that the music stored in the SD card is actually present in the library. So, I don't think it is a permission issue.

**Comment by mardous** [comment]
> ![Image](https://github.com/user-attachments/assets/055ef76b-193a-4f63-96f0-8ce911c1b676)
> 
> No permission denied message. Just that SD card does not appear in the selection dialog. I want to only whitelist the Music folder in the SD card. Only the internal storage is selectable. (When I go one folder up, there is nothing there.) Note, however, that the music stored in the SD card is actually present in the library. So, I don't think it is a permission issue.

I see, thanks for explaining it better. We need to add a storage medium selector when we get to `/storage/`. Taking some of the code already used in the library _Folders_ fragment, the same thing can be implemented here.

**Comment by LatringDay** [comment]
Just updated the app. Whitelist/blacklist optiond now show folders but only From the internal storage. SD card is invisible

**Comment by mardous** [comment]
> Just updated the app. Whitelist/blacklist optiond now show folders but only From the internal storage. SD card is invisible 

Android is restricting reading the contents of the SD card directly. I'm considering the possibility of the user manually entering the path of the folders on the SD card, at least as a temporary solution.

**Comment by LatringDay** [comment]
This Version fixes the whitelist/blacklist SD card view but the folders in the folders tab located on the SD card are still empty. They show no songs except the only folder that i added 2 days ago

**Comment by mardous** [comment]
> This Version fixes the whitelist/blacklist SD card view but the folders in the folders tab located on the SD card are still empty. They show no songs except the only folder that i added 2 days ago

I'll close this issue, as the main reason for opening it has been resolved. We'll address everything related to what you mentioned in #24.
